services:
    # backend:
    #   build: .
    #   ports:
    #     - "8080:8080"
    #   depends_on:
    #     - db
    #   environment:
    #     - DB_HOST=db
    #     - DB_USER=postgres
    #     - DB_PASSWORD=postgres
    #     - DB_NAME=finance-tracker
    #     - DB_PORT=5432
    #     - DB_SSL_MODE=disable
    #     - SERVER_HOST=0.0.0.0
    #     - SERVER_PORT=8080
    #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #     - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
    #     - JWT_SECRET=${JWT_SECRET}
    #     - JWT_EXPIRES_AT=${JWT_EXPIRES_AT}

    db:
        image: postgres:18-alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
    postgres_data:
