services:
    # backend:
    #     build: .
    #     container_name: backend
    #     restart: always
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - db
    #     environment:
    #         - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    #         - HOST=${HOST}
    #         - PORT=${PORT}

    #         - DB_HOST=db
    #         - DB_USER=${DB_USER}
    #         - DB_PASSWORD=${DB_PASSWORD}
    #         - DB_NAME=${DB_NAME}
    #         - DB_PORT=${DB_PORT}
    #         - DB_SSL_MODE=${DB_SSL_MODE}

    #         - JWT_SECRET=${JWT_SECRET}
    #         - JWT_EXPIRES_AT=${JWT_EXPIRES_IN}
    #         - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

    #         - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    #         - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    #         - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}

    #         - RATE_LIMITER_MAX=${RATE_LIMITER_MAX}
    #         - RATE_LIMITER_DURATION_MINUTES=${RATE_LIMITER_DURATION_MINUTES}

    db:
        image: postgres:18-alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
    postgres_data:
